version: '3'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ivtc
        uid: 1000
    image: ivtc-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - ivtc-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - ivtc-network

  # MySQL Service
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - ivtc-network

networks:
  ivtc-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
